export const TEMPLATE_STYLES = {
  none: {
    name: "Sem template",
    kind: "standard",
  },

  // =========================
  // MONOCROMÁTICOS - LINHA 1
  // =========================

  mono_plain_bottom: {
    name: "Mono Plain Bottom",
    kind: "card",
    outerBg: "#F7F7F7",
    qrColor: "#1E1E22",
    cornerColor: "#1E1E22",
    card: {
      fill: "#F7F7F7",
      radius: 24,
    },
    panel: {
      variant: "none",
      inset: 22,
      topExtra: 6,
      bottomExtra: 48,
      qrPaddingX: 10,
      qrPaddingTop: 0,
      qrPaddingBottom: 0,
    },
    label: {
      kind: "plain_bottom",
      yFromBottom: 42,
      x: 24,
      widthInset: 48,
      height: 34,
      textColor: "#1E1E22",
      fontScale: 0.92,
    },
  },

  mono_scan_code_arrow_top: {
    name: "Mono Scan Code Arrow Top",
    kind: "card",
    outerBg: "#F7F7F7",
    qrColor: "#FFFFFF",
    cornerColor: "#FFFFFF",
    card: {
      fill: "#F7F7F7",
      radius: 24,
    },
    panel: {
      variant: "solid",
      fill: "#1E1E22",
      inset: 22,
      topExtra: 52,
      bottomExtra: 18,
      qrPaddingX: 20,
      qrPaddingTop: 18,
      qrPaddingBottom: 18,
      radius: 18,
    },
    label: {
      kind: "plain_top",
      y: 16,
      x: 26,
      widthInset: 52,
      height: 30,
      textColor: "#1E1E22",
      fontScale: 0.95,
    },
    icon: {
      kind: "arrow_down",
      anchor: "below_label",
      gap: 10,
      width: 40,
      height: 22,
      color: "#1E1E22",
    },
  },

  mono_corners_bar_bottom: {
    name: "Mono Corners Bar Bottom",
    kind: "card",
    outerBg: "#F7F7F7",
    qrColor: "#1E1E22",
    cornerColor: "#1E1E22",
    card: {
      fill: "#F7F7F7",
      radius: 24,
    },
    panel: {
      variant: "none",
      inset: 24,
      topExtra: 6,
      bottomExtra: 54,
      qrPaddingX: 10,
      qrPaddingTop: 6,
      qrPaddingBottom: 0,
    },
    cta: {
      enabled: true,
      x: 24,
      yFromBottom: 54,
      width: 182,
      height: 34,
      radius: 6,
      fill: "#1E1E22",
      textColor: "#FFFFFF",
      text: "SCAN QR CODE",
      fontScale: 0.62,
    },
    frame: {
      type: "corners",
      color: "#1E1E22",
      lineWidth: 6,
      lengthRatio: 0.19,
      insetRatio: -0.02,
    },
  },

  mono_outline_bottom_text: {
    name: "Mono Outline Bottom Text",
    kind: "card",
    outerBg: "#F7F7F7",
    qrColor: "#1E1E22",
    cornerColor: "#1E1E22",
    card: {
      fill: "#F7F7F7",
      radius: 24,
    },
    panel: {
      variant: "outline",
      fill: null,
      stroke: "#1E1E22",
      strokeWidth: 5,
      inset: 20,
      topExtra: 6,
      bottomExtra: 54,
      qrPaddingX: 18,
      qrPaddingTop: 14,
      qrPaddingBottom: 14,
      radius: 2,
    },
    label: {
      kind: "plain_bottom",
      yFromBottom: 42,
      x: 28,
      widthInset: 56,
      height: 30,
      textColor: "#1E1E22",
      fontScale: 0.88,
    },
  },

  // =========================
  // MONOCROMÁTICOS - LINHA 2
  // =========================

  mono_pill_bottom: {
    name: "Mono Pill Bottom",
    kind: "card",
    outerBg: "#F7F7F7",
    qrColor: "#1E1E22",
    cornerColor: "#1E1E22",
    card: {
      fill: "#F7F7F7",
      radius: 24,
    },
    panel: {
      variant: "none",
      inset: 22,
      topExtra: 8,
      bottomExtra: 54,
      qrPaddingX: 10,
      qrPaddingTop: 0,
      qrPaddingBottom: 0,
    },
    label: {
      kind: "pill_bottom",
      yFromBottom: 48,
      x: 24,
      widthInset: 48,
      height: 34,
      radius: 18,
      fill: "#1E1E22",
      textColor: "#FFFFFF",
      pointer: false,
      fontScale: 0.72,
    },
  },

  mono_corners_pill_bottom_arrow_left: {
    name: "Mono Corners Pill Bottom Arrow Left",
    kind: "card",
    outerBg: "#F7F7F7",
    qrColor: "#1E1E22",
    cornerColor: "#1E1E22",
    card: {
      fill: "#F7F7F7",
      radius: 24,
    },
    panel: {
      variant: "none",
      inset: 30,
      topExtra: 34,
      bottomExtra: 74,
      qrPaddingX: 8,
      qrPaddingTop: 0,
      qrPaddingBottom: 0,
    },
    label: {
      kind: "pill_bottom",
      yFromBottom: 48,
      x: 38,
      widthInset: 76,
      height: 34,
      radius: 18,
      fill: "#1E1E22",
      textColor: "#FFFFFF",
      pointer: false,
      fontScale: 0.8,
    },
    frame: {
      type: "corners",
      color: "#1E1E22",
      lineWidth: 5,
      lengthRatio: 0.22,
      insetRatio: -0.04,
    },
    icon: {
      kind: "arrow_curve",
      anchor: "left_bottom",
      left: 14,
      bottom: 56,
      width: 34,
      height: 34,
      lineWidth: 4,
      color: "#1E1E22",
    },
  },

  mono_dark_panel_arrow_top: {
    name: "Mono Dark Panel Arrow Top",
    kind: "card",
    outerBg: "#F7F7F7",
    qrColor: "#FFFFFF",
    cornerColor: "#FFFFFF",
    card: {
      fill: "#F7F7F7",
      radius: 24,
    },
    panel: {
      variant: "solid",
      fill: "#1E1E22",
      inset: 24,
      topExtra: 70,
      bottomExtra: 14,
      qrPaddingX: 18,
      qrPaddingTop: 20,
      qrPaddingBottom: 18,
      radius: 18,
    },
    cta: {
      enabled: true,
      x: 22,
      y: 12,
      width: 186,
      height: 34,
      radius: 6,
      fill: "#1E1E22",
      textColor: "#FFFFFF",
      text: "SCAN ME",
      fontScale: 0.7,
    },
    icon: {
      kind: "arrow_down",
      anchor: "top_inside",
      y: 52,
      width: 44,
      height: 26,
      color: "#1E1E22",
    },
    frame: {
      type: "corners",
      color: "#FFFFFF",
      lineWidth: 6,
      lengthRatio: 0.19,
      insetRatio: 0.02,
    },
  },

  mono_plain_top_curve_right: {
    name: "Mono Plain Top Curve Right",
    kind: "card",
    outerBg: "#F7F7F7",
    qrColor: "#1E1E22",
    cornerColor: "#1E1E22",
    card: {
      fill: "#F7F7F7",
      radius: 24,
    },
    panel: {
      variant: "none",
      inset: 24,
      topExtra: 50,
      bottomExtra: 16,
      qrPaddingX: 10,
      qrPaddingTop: 2,
      qrPaddingBottom: 0,
    },
    label: {
      kind: "plain_top",
      y: 18,
      x: 20,
      widthInset: 40,
      height: 28,
      textColor: "#1E1E22",
      fontScale: 0.82,
    },
    icon: {
      kind: "arrow_curve",
      anchor: "right_top",
      top: 18,
      right: 14,
      width: 36,
      height: 36,
      lineWidth: 4,
      color: "#1E1E22",
    },
  },

  // =========================
  // COLORIDOS - LINHA 1
  // =========================

  green_top_badge_corners: {
    name: "Green Top Badge Corners",
    kind: "card",
    outerBg: "#67BB5B",
    qrColor: "#FFFFFF",
    cornerColor: "#FFFFFF",
    card: {
      fill: "#67BB5B",
      radius: 22,
    },
    panel: {
      variant: "none",
      inset: 26,
      topExtra: 42,
      bottomExtra: 24,
      qrPaddingX: 10,
      qrPaddingTop: 2,
      qrPaddingBottom: 0,
    },
    label: {
      kind: "pill_top",
      y: 12,
      x: 16,
      widthInset: 32,
      height: 34,
      radius: 8,
      fill: "#FFFFFF",
      textColor: "#67BB5B",
      pointer: true,
      pointerSize: 8,
      fontScale: 0.7,
    },
    frame: {
      type: "corners",
      color: "#FFFFFF",
      lineWidth: 5,
      lengthRatio: 0.18,
      insetRatio: -0.02,
    },
  },

  red_top_badge_panel: {
    name: "Red Top Badge Panel",
    kind: "card",
    outerBg: "#DE6669",
    qrColor: "#DE6669",
    cornerColor: "#DE6669",
    card: {
      fill: "#DE6669",
      radius: 22,
    },
    panel: {
      variant: "solid",
      fill: "#FFFFFF",
      inset: 22,
      topExtra: 32,
      bottomExtra: 16,
      qrPaddingX: 14,
      qrPaddingTop: 16,
      qrPaddingBottom: 14,
      radius: 12,
    },
    label: {
      kind: "outline_top",
      y: 0,
      x: 28,
      widthInset: 56,
      height: 34,
      radius: 8,
      fill: "#DE6669",
      stroke: "#F5D9DA",
      strokeWidth: 2,
      textColor: "#FFFFFF",
      pointer: false,
      fontScale: 0.66,
    },
  },

  yellow_card_bottom_badge: {
    name: "Yellow Card Bottom Badge",
    kind: "card",
    outerBg: "#E6C33E",
    qrColor: "#FFFFFF",
    cornerColor: "#FFFFFF",
    card: {
      fill: "#E6C33E",
      radius: 22,
    },
    panel: {
      variant: "none",
      inset: 24,
      topExtra: 6,
      bottomExtra: 48,
      qrPaddingX: 10,
      qrPaddingTop: 0,
      qrPaddingBottom: 0,
    },
    label: {
      kind: "pill_bottom",
      yFromBottom: 46,
      x: 18,
      widthInset: 36,
      height: 32,
      radius: 8,
      fill: "#FFFFFF",
      textColor: "#E6C33E",
      pointer: false,
      fontScale: 0.72,
    },
  },

  blue_outline_top_badge_panel: {
    name: "Blue Outline Top Badge Panel",
    kind: "card",
    outerBg: "#FFFFFF",
    qrColor: "#5D7FDE",
    cornerColor: "#5D7FDE",
    card: {
      fill: "#FFFFFF",
      stroke: "#5D7FDE",
      strokeWidth: 4,
      radius: 22,
    },
    panel: {
      variant: "solid",
      fill: "#5D7FDE",
      inset: 22,
      topExtra: 34,
      bottomExtra: 16,
      qrPaddingX: 14,
      qrPaddingTop: 16,
      qrPaddingBottom: 14,
      radius: 12,
    },
    label: {
      kind: "outline_top",
      y: 0,
      x: 20,
      widthInset: 40,
      height: 34,
      radius: 8,
      fill: "#FFFFFF",
      stroke: "#5D7FDE",
      strokeWidth: 2,
      textColor: "#5D7FDE",
      pointer: true,
      pointerSize: 7,
      fontScale: 0.66,
    },
  },

  green_bottom_badge_corners: {
    name: "Green Bottom Badge Corners",
    kind: "card",
    outerBg: "#67BB5B",
    qrColor: "#FFFFFF",
    cornerColor: "#FFFFFF",
    card: {
      fill: "#67BB5B",
      radius: 22,
    },
    panel: {
      variant: "none",
      inset: 22,
      topExtra: 6,
      bottomExtra: 52,
      qrPaddingX: 10,
      qrPaddingTop: 4,
      qrPaddingBottom: 0,
    },
    label: {
      kind: "pill_bottom",
      yFromBottom: 42,
      x: 18,
      widthInset: 36,
      height: 32,
      radius: 8,
      fill: "#FFFFFF",
      textColor: "#67BB5B",
      pointer: true,
      pointerSize: 7,
      fontScale: 0.72,
    },
    frame: {
      type: "corners",
      color: "#FFFFFF",
      lineWidth: 5,
      lengthRatio: 0.18,
      insetRatio: -0.02,
    },
  },

  // =========================
  // COLORIDOS - LINHA 2
  // =========================

  yellow_arrow_top_corners: {
    name: "Yellow Arrow Top Corners",
    kind: "card",
    outerBg: "#E6C33E",
    qrColor: "#FFFFFF",
    cornerColor: "#FFFFFF",
    card: {
      fill: "#E6C33E",
      radius: 22,
    },
    panel: {
      variant: "none",
      inset: 22,
      topExtra: 64,
      bottomExtra: 18,
      qrPaddingX: 8,
      qrPaddingTop: 0,
      qrPaddingBottom: 0,
    },
    label: {
      kind: "plain_top",
      y: 18,
      x: 18,
      widthInset: 36,
      height: 30,
      textColor: "#FFFFFF",
      fontScale: 0.72,
    },
    icon: {
      kind: "arrow_down",
      anchor: "top_inside",
      y: 52,
      width: 40,
      height: 22,
      color: "#FFFFFF",
    },
    frame: {
      type: "corners",
      color: "#FFFFFF",
      lineWidth: 5,
      lengthRatio: 0.18,
      insetRatio: -0.02,
    },
  },

  blue_corners_bar_bottom: {
    name: "Blue Corners Bar Bottom",
    kind: "card",
    outerBg: "#FFFFFF",
    qrColor: "#5D7FDE",
    cornerColor: "#5D7FDE",
    card: {
      fill: "#FFFFFF",
      stroke: "#5D7FDE",
      strokeWidth: 4,
      radius: 22,
    },
    panel: {
      variant: "none",
      inset: 24,
      topExtra: 18,
      bottomExtra: 56,
      qrPaddingX: 10,
      qrPaddingTop: 0,
      qrPaddingBottom: 0,
    },
    cta: {
      enabled: true,
      x: 18,
      yFromBottom: 42,
      width: 142,
      height: 30,
      radius: 8,
      fill: "#5D7FDE",
      textColor: "#FFFFFF",
      text: "SCAN ME",
      fontScale: 0.68,
    },
    frame: {
      type: "corners",
      color: "#5D7FDE",
      lineWidth: 5,
      lengthRatio: 0.18,
      insetRatio: -0.02,
    },
  },

  red_top_badge_white_panel: {
    name: "Red Top Badge White Panel",
    kind: "card",
    outerBg: "#DE6669",
    qrColor: "#DE6669",
    cornerColor: "#DE6669",
    card: {
      fill: "#DE6669",
      radius: 22,
    },
    panel: {
      variant: "solid",
      fill: "#FFFFFF",
      inset: 22,
      topExtra: 36,
      bottomExtra: 14,
      qrPaddingX: 14,
      qrPaddingTop: 14,
      qrPaddingBottom: 14,
      radius: 12,
    },
    label: {
      kind: "pill_top",
      y: 0,
      x: 18,
      widthInset: 36,
      height: 34,
      radius: 8,
      fill: "#DE6669",
      textColor: "#FFFFFF",
      pointer: true,
      pointerSize: 8,
      fontScale: 0.72,
    },
  },

  green_bottom_badge_white_panel: {
    name: "Green Bottom Badge White Panel",
    kind: "card",
    outerBg: "#67BB5B",
    qrColor: "#67BB5B",
    cornerColor: "#67BB5B",
    card: {
      fill: "#67BB5B",
      radius: 22,
    },
    panel: {
      variant: "solid",
      fill: "#FFFFFF",
      inset: 22,
      topExtra: 18,
      bottomExtra: 48,
      qrPaddingX: 14,
      qrPaddingTop: 16,
      qrPaddingBottom: 14,
      radius: 12,
    },
    label: {
      kind: "pill_bottom",
      yFromBottom: 42,
      x: 18,
      widthInset: 36,
      height: 34,
      radius: 8,
      fill: "#67BB5B",
      textColor: "#FFFFFF",
      pointer: true,
      pointerSize: 8,
      fontScale: 0.7,
    },
    frame: {
      type: "corners",
      color: "#67BB5B",
      lineWidth: 5,
      lengthRatio: 0.18,
      insetRatio: -0.02,
    },
  },

  blue_full_panel: {
    name: "Blue Full Panel",
    kind: "card",
    outerBg: "#5D7FDE",
    qrColor: "#FFFFFF",
    cornerColor: "#FFFFFF",
    card: {
      fill: "#5D7FDE",
      radius: 22,
    },
    panel: {
      variant: "solid",
      fill: "#5D7FDE",
      inset: 18,
      topExtra: 40,
      bottomExtra: 18,
      qrPaddingX: 18,
      qrPaddingTop: 18,
      qrPaddingBottom: 18,
      radius: 10,
    },
    label: {
      kind: "plain_top",
      y: 18,
      x: 20,
      widthInset: 40,
      height: 28,
      textColor: "#FFFFFF",
      fontScale: 0.68,
    },
    frame: {
      type: "panel_outline",
      color: "#FFFFFF",
      lineWidth: 4,
    },
  },
};

export function getTemplateStyle(templateStyle) {
  return TEMPLATE_STYLES[templateStyle] ?? TEMPLATE_STYLES.none;
}
